# Generated by Django 2.2.3 on 2019-07-20 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190713_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 7, 20, 12, 59, 37, 110414)),
        ),
    ]
